use crate::ast::{self, BinOp, Expr, FnDef, Module, Prim, TypeExpr};
use std::collections::HashMap;

pub struct Generated {
    pub crate_name: String,
    pub cargo_toml: String,
    pub source_rs: String,
    pub is_binary: bool,
}

pub fn codegen(module: &Module) -> Generated {
    let crate_name = module.name.replace('.', "_");
    let is_binary = module.fns.iter().any(|f| f.name == "main");

    let mut src = String::new();
    src.push_str("// generated by alva v0.1.0 -- do not edit by hand\n");
    src.push_str(
        "#![allow(unused_parens, unused_variables, unused_imports, dead_code, while_true)]\n",
    );
    src.push_str("use std::collections::HashMap;\n");
    src.push_str(&format!("// source module: {}\n\n", module.name));
    for t in &module.types {
        src.push_str(&gen_type(t));
        src.push('\n');
    }
    for e in &module.exts {
        src.push_str(&gen_extern(e));
        src.push('\n');
    }
    let exports: std::collections::HashSet<&str> =
        module.exports.iter().map(|s| s.as_str()).collect();
    let result_fns: std::collections::HashSet<&str> = module
        .fns
        .iter()
        .filter(|f| matches!(f.returns, TypeExpr::Result(..)))
        .map(|f| f.name.as_str())
        .chain(
            module
                .exts
                .iter()
                .filter(|e| matches!(e.returns, TypeExpr::Result(..)))
                .map(|e| e.name.as_str()),
        )
        .collect();
    let deps: std::collections::HashSet<String> =
        module.deps.iter().map(|(n, _)| n.clone()).collect();
    for f in &module.fns {
        src.push_str(&gen_fn(f, &module.name, &exports, &result_fns, &deps));
        src.push('\n');
    }
    for t in &module.tests {
        src.push_str(&gen_test(t, &deps));
        src.push('\n');
    }
    for b in &module.benches {
        src.push_str(&gen_bench(b, &deps));
        src.push('\n');
    }
    src.push_str(GLUE_SOURCE);

    let mut cargo = String::new();
    cargo.push_str("[package]\n");
    cargo.push_str(&format!("name = \"{crate_name}\"\n"));
    cargo.push_str(&format!("version = \"{}\"\n", module.version));
    cargo.push_str("edition = \"2021\"\n\n[dependencies]\n");
    let declared: std::collections::HashSet<&str> =
        module.rust_deps.iter().map(|(c, _)| c.as_str()).collect();
    if !declared.contains("sha2") {
        // glue 的 fs 原语依赖 sha2（内容寻址校验），对所有生成 crate 提供。
        cargo.push_str("sha2 = \"0.10\"\n");
    }
    for (c, v) in &module.rust_deps {
        cargo.push_str(&format!("{c} = \"{v}\"\n"));
    }

    Generated {
        crate_name,
        cargo_toml: cargo,
        source_rs: src,
        is_binary,
    }
}

fn gen_type(t: &ast::TypeDef) -> String {
    match &t.kind {
        ast::TypeKind::Record(fields) => {
            let mut s = format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {} {{\n",
                t.name
            );
            for (n, te) in fields {
                s.push_str(&format!("    pub {n}: {},\n", ty(te)));
            }
            s.push_str("}\n");
            s
        }
        ast::TypeKind::Enum(variants) => {
            let mut s = format!(
                "#[derive(Debug, Clone, PartialEq)]\npub enum {} {{\n",
                t.name
            );
            for v in variants {
                s.push_str(&format!("    {},\n", to_pascal(v)));
            }
            s.push_str("}\n");
            s
        }
        ast::TypeKind::Alias(te) => format!("pub type {} = {};\n", t.name, ty(te)),
    }
}

fn gen_fn(
    f: &FnDef,
    module_name: &str,
    exports: &std::collections::HashSet<&str>,
    result_fns: &std::collections::HashSet<&str>,
    deps: &std::collections::HashSet<String>,
) -> String {
    let params: Vec<String> = f
        .params
        .iter()
        .map(|(n, t)| format!("{n}: {}", ty(t)))
        .collect();
    let mut s = String::new();
    let vis = if exports.contains(f.name.as_str()) {
        "pub "
    } else {
        ""
    };
    s.push_str(&format!(
        "{vis}fn {}({}) -> {} {{\n",
        f.name,
        params.join(", "),
        ty(&f.returns)
    ));

    let mut ctx = Ctx::new();
    ctx.deps = deps.clone();
    for (n, _) in &f.params {
        ctx.vars.insert(n.clone(), n.clone());
    }

    for pre in &f.pre {
        s.push_str(&format!(
            "    debug_assert!({}, \"[{module_name}.{}] precondition violated\");\n",
            gen_expr(pre, &ctx),
            f.name
        ));
    }
    for inv in &f.inv {
        s.push_str(&format!(
            "    debug_assert!({}, \"[{module_name}.{}] invariant violated\");\n",
            gen_expr(inv, &ctx),
            f.name
        ));
    }

    let body = gen_block(&f.body, &ctx);
    let returns_result = matches!(f.returns, TypeExpr::Result(..));
    let last_is_result = f
        .body
        .last()
        .map(|e| produces_result(e, result_fns))
        .unwrap_or(false);
    let body = if returns_result && !last_is_result {
        format!("Ok({body})")
    } else {
        body
    };

    if f.post.is_empty() && f.inv.is_empty() {
        s.push_str(&format!("    {body}\n"));
    } else {
        s.push_str(&format!("    let __result = {body};\n"));
        let mut pctx = ctx;
        pctx.vars
            .insert("result".to_string(), "__result".to_string());
        // 不变量在函数出口再次检查（result 可见）
        for inv in &f.inv {
            s.push_str(&format!(
                "    debug_assert!({}, \"[{module_name}.{}] invariant violated at exit\");\n",
                gen_expr(inv, &pctx),
                f.name
            ));
        }
        for post in &f.post {
            s.push_str(&format!(
                "    debug_assert!({}, \"[{module_name}.{}] postcondition violated\");\n",
                gen_expr(post, &pctx),
                f.name
            ));
        }
        s.push_str("    __result\n");
    }
    s.push_str("}\n");
    s
}

fn gen_extern(e: &ast::ExternDef) -> String {
    let params: Vec<String> = e
        .params
        .iter()
        .map(|(n, t)| format!("{n}: {}", ty(t)))
        .collect();
    let mut body = e.template.clone();
    for (n, _) in &e.params {
        body = body.replace(&format!("{{{n}}}"), n);
    }
    format!(
        "fn {}({}) -> {} {{\n    {}\n}}\n",
        extern_wrapper_name(&e.name),
        params.join(", "),
        ty(&e.returns),
        body
    )
}

// 判断表达式是否已经产生 result 类型（避免自动 Ok 包装）
fn produces_result(e: &Expr, result_fns: &std::collections::HashSet<&str>) -> bool {
    match e {
        Expr::Ok(..) | Expr::Err(..) | Expr::Try(..) | Expr::Lookup(..) | Expr::ParseInt(..) => {
            true
        }
        Expr::Call(name, _, _) => name == "lookup" || result_fns.contains(name.as_str()),
        Expr::If(_, t, e2, _) => produces_result(t, result_fns) || produces_result(e2, result_fns),
        Expr::Block(exprs, _) => exprs
            .last()
            .map(|x| produces_result(x, result_fns))
            .unwrap_or(false),
        Expr::Let(_, _, _, body, _) => produces_result(body, result_fns),
        _ => false,
    }
}

fn extern_wrapper_name(name: &str) -> String {
    format!("__ext_{}", name.replace('.', "_"))
}

fn gen_test(t: &ast::TestDef, deps: &std::collections::HashSet<String>) -> String {
    let mut ctx = Ctx::new();
    ctx.deps = deps.clone();
    format!(
        "#[test]\nfn test_{}() {{\n    assert!({});\n}}\n",
        t.name,
        gen_expr(&t.body, &ctx)
    )
}

fn gen_bench(b: &ast::BenchDef, deps: &std::collections::HashSet<String>) -> String {
    let mut ctx = Ctx::new();
    ctx.deps = deps.clone();
    let mut s = String::new();
    s.push_str(&format!("#[test]\nfn bench_{}() {{\n", b.name));
    for e in &b.setup {
        s.push_str(&format!("    {};\n", gen_stmt(e, &ctx)));
    }
    s.push_str(&format!(
        "    let _ = std::hint::black_box({});\n",
        gen_expr(&b.body, &ctx)
    ));
    s.push_str("    let __rounds = 10i64;\n");
    s.push_str("    let mut __total = 0.0f64;\n");
    s.push_str("    let mut __min = f64::MAX;\n");
    s.push_str("    let mut __max = 0.0f64;\n");
    s.push_str("    for __r in 0..__rounds {\n");
    s.push_str("        let __t0 = std::time::SystemTime::now();\n");
    s.push_str(&format!(
        "        let _ = std::hint::black_box({});\n",
        gen_expr(&b.body, &ctx)
    ));
    s.push_str("        let __t1 = std::time::SystemTime::now();\n");
    s.push_str("        let __ms = __t1.duration_since(__t0).unwrap().as_secs_f64() * 1000.0;\n");
    s.push_str("        __total += __ms;\n");
    s.push_str("        if __ms < __min { __min = __ms; }\n");
    s.push_str("        if __ms > __max { __max = __ms; }\n");
    s.push_str("    }\n");
    s.push_str("    let __avg = __total / __rounds as f64;\n");
    s.push_str(&format!(
        "    println!(\"[bench {}] rounds={{}} min={{:.2}}ms max={{:.2}}ms avg={{:.2}}ms\", __rounds, __min, __max, __avg);\n",
        b.name
    ));
    if let Some(ms) = b.ms_budget {
        s.push_str(&format!(
            "    assert!(__avg <= {ms}f64, \"[bench {}] budget violated: avg {{:.2}}ms > {ms}ms\", __avg);\n",
            b.name
        ));
    }
    s.push_str("}\n");
    s
}

// 语句化输出：let 绑定以语句形式发出（绑定在所在块内持续可见），用于 bench setup
fn gen_stmt(e: &Expr, ctx: &Ctx) -> String {
    match e {
        Expr::Let(name, declared, value, body, _) => {
            let ann = declared
                .as_ref()
                .map(|t| format!(": {}", ty(t)))
                .unwrap_or_default();
            let mut c2 = ctx.clone();
            c2.vars.insert(name.clone(), name.clone());
            format!(
                "let {name}{ann} = {}; {}",
                gen_expr(value, ctx),
                gen_stmt(body, &c2)
            )
        }
        _ => gen_expr(e, ctx),
    }
}

#[derive(Clone)]
struct Ctx {
    vars: HashMap<String, String>,
    deps: std::collections::HashSet<String>,
}

impl Ctx {
    fn new() -> Self {
        Ctx {
            vars: HashMap::new(),
            deps: std::collections::HashSet::new(),
        }
    }

    fn get(&self, name: &str) -> String {
        self.vars
            .get(name)
            .cloned()
            .unwrap_or_else(|| name.to_string())
    }
}

fn gen_block(exprs: &[Expr], ctx: &Ctx) -> String {
    if exprs.len() == 1 {
        return gen_expr(&exprs[0], ctx);
    }
    let mut parts = Vec::new();
    for (i, x) in exprs.iter().enumerate() {
        let g = gen_expr(x, ctx);
        if i + 1 == exprs.len() {
            parts.push(g);
        } else {
            parts.push(format!("{g};"));
        }
    }
    format!("{{ {} }}", parts.join(" "))
}

fn gen_expr(e: &Expr, ctx: &Ctx) -> String {
    match e {
        Expr::Int(v, _) => format!("{v}i64"),
        Expr::UInt(v, _) => format!("{v}u64"),
        Expr::Float(v, _) => format!("{v}f64"),
        Expr::Str(s, _) => rust_string(s),
        Expr::Bool(b, _) => b.to_string(),
        Expr::Bytes(v, _) => {
            let parts: Vec<String> = v.iter().map(|b| format!("0x{b:02x}u8")).collect();
            format!("vec![{}]", parts.join(", "))
        }
        Expr::Nil(_) => "()".to_string(),
        Expr::Ref(name, _) => format!("{}.clone()", ctx.get(name)),
        Expr::Call(name, args, _) => {
            let a: Vec<String> = args.iter().map(|x| gen_expr(x, ctx)).collect();
            if name == "io.print" {
                format!("println!(\"{{}}\", {})", a.join(", "))
            } else if name == "io.print_debug" {
                format!("println!(\"{{:?}}\", {})", a.join(", "))
            } else if name == "sys.now_ms" {
                "std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_millis() as i64".to_string()
            } else if name == "len" {
                format!("{}.len() as i64", maybe_paren(&a[0]))
            } else if name == "get" {
                format!("{}[({}) as usize].clone()", maybe_paren(&a[0]), a[1])
            } else if name == "append" {
                format!("{{ let mut __v = {}; __v.push({}); __v }}", a[0], a[1])
            } else if name == "set" {
                format!("{{ let mut __m = {}; __m.insert({}, {}); __m }}", a[0], a[1], a[2])
            } else if name == "lookup" {
                format!("{}.get(&{}).cloned().ok_or(())", maybe_paren(&a[0]), maybe_paren(&a[1]))
            } else if name == "contains" {
                format!("{}.contains_key(&{})", maybe_paren(&a[0]), maybe_paren(&a[1]))
            } else if name == "remove" {
                format!("{{ let mut __m = {}; __m.remove(&{}); __m }}", a[0], maybe_paren(&a[1]))
            } else if name == "keys" {
                format!("{}.keys().cloned().collect::<Vec<_>>()", maybe_paren(&a[0]))
            } else if name == "unwrap" {
                format!("{}.expect(\"[alva] unwrap on Err\")", maybe_paren(&a[0]))
            } else if name == "slice" {
                format!(
                    "{}[{} as usize..{} as usize].to_vec()",
                    maybe_paren(&a[0]),
                    maybe_paren(&a[1]),
                    maybe_paren(&a[2])
                )
            } else if name == "split" {
                format!(
                    "{}.split(&{}).map(|x| x.to_string()).collect::<Vec<String>>()",
                    maybe_paren(&a[0]),
                    maybe_paren(&a[1])
                )
            } else if name == "concat" {
                format!("format!(\"{{}}{{}}\", {}, {})", a[0], a[1])
            } else if name == "to-string" {
                format!("format!(\"{{}}\", {})", a[0])
            } else if name == "to-bytes" {
                format!("{}.into_bytes()", maybe_paren(&a[0]))
            } else if name == "is-ok" {
                format!("{}.is_ok()", maybe_paren(&a[0]))
            } else if name == "join" {
                format!("{}.join(&{})", maybe_paren(&a[0]), maybe_paren(&a[1]))
            } else if name == "strip-prefix" {
                format!(
                    "{}.strip_prefix(&{}).map(|x| x.to_string()).unwrap_or_else(|| {}.clone())",
                    maybe_paren(&a[0]),
                    maybe_paren(&a[1]),
                    a[0]
                )
            } else if name == "before" {
                format!(
                    "{}.split(&{}).next().unwrap_or(\"\").to_string()",
                    maybe_paren(&a[0]),
                    maybe_paren(&a[1])
                )
            } else if name == "ends-with" {
                format!("{}.ends_with(&{})", maybe_paren(&a[0]), maybe_paren(&a[1]))
            } else if name == "sort" {
                format!("{{ let mut __v = {}; __v.sort(); __v }}", a[0])
            } else if name == "url-decode" {
                format!("glue::url_decode({})", a[0])
            } else if name == "to-hex" {
                format!(
                    "{{ let __b = {}; let mut __s = String::new(); for __x in &__b {{ __s.push_str(&format!(\"{{:02x}}\", __x)); }} __s }}",
                    a[0]
                )
            } else if name == "ct-eq" {
                format!("glue::ct_eq({}, {})", a[0], a[1])
            } else if name.contains('.') {
                let last_dot = name.rfind('.').unwrap_or(0);
                let module = &name[..last_dot];
                if ctx.deps.contains(module) {
                    format!(
                        "crate::{}::{}({})",
                        module.replace('.', "_"),
                        &name[last_dot + 1..],
                        a.join(", ")
                    )
                } else {
                    format!("{}({})", extern_wrapper_name(name), a.join(", "))
                }
            } else {
                format!("{}({})", name, a.join(", "))
            }
        }
        Expr::Bin(op, a, b, _) => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!(
                "{} {op_s} {}",
                maybe_paren(&gen_expr(a, ctx)),
                maybe_paren(&gen_expr(b, ctx))
            )
        }
        Expr::Not(x, _) => format!("!{}", maybe_paren(&gen_expr(x, ctx))),
        Expr::If(c, t, e2, _) => format!(
            "if {} {{ {} }} else {{ {} }}",
            maybe_paren(&gen_expr(c, ctx)),
            gen_expr(t, ctx),
            gen_expr(e2, ctx)
        ),
        Expr::Let(name, declared, value, body, _) => {
            let ann = declared
                .as_ref()
                .map(|t| format!(": {}", ty(t)))
                .unwrap_or_default();
            let mut c2 = ctx.clone();
            c2.vars.insert(name.clone(), name.clone());
            format!(
                "{{ let {name}{ann} = {}; {} }}",
                gen_expr(value, ctx),
                gen_expr(body, &c2)
            )
        }
        Expr::Block(exprs, _) => gen_block(exprs, ctx),
        Expr::VecLit(_, elems, _) => {
            if elems.is_empty() {
                "Vec::new()".to_string()
            } else {
                let parts: Vec<String> = elems.iter().map(|e| gen_expr(e, ctx)).collect();
                format!("vec![{}]", parts.join(", "))
            }
        }
        Expr::Len(v, _) => format!("{}.len() as i64", maybe_paren(&gen_expr(v, ctx))),
        Expr::Get(v, i, _) => format!(
            "{}[({}) as usize].clone()",
            maybe_paren(&gen_expr(v, ctx)),
            gen_expr(i, ctx)
        ),
        Expr::Append(v, x, _) => format!(
            "{{ let mut __v = {}; __v.push({}); __v }}",
            gen_expr(v, ctx),
            gen_expr(x, ctx)
        ),
        Expr::As(t, x, _) => format!("({}) as {}", gen_expr(x, ctx), ty(t)),
        Expr::Fold(idx, lo, hi, acc_name, acc_ty, init, body, _) => {
            let mut c2 = ctx.clone();
            c2.vars.insert(idx.clone(), "i".to_string());
            c2.vars.insert(acc_name.clone(), "acc".to_string());
            format!(
                "{{ let mut acc: {} = {}; for i in {}..{} {{ acc = {}; }} acc }}",
                ty(acc_ty),
                gen_expr(init, ctx),
                maybe_paren(&gen_expr(lo, ctx)),
                maybe_paren(&gen_expr(hi, ctx)),
                gen_expr(body, &c2)
            )
        }
        Expr::Variant(ty_name, vname, _) => format!("{}::{}", ty_name, to_pascal(vname)),
        Expr::Match(ty_name, value, cases, _) => {
            let mut arms = Vec::new();
            for (vname, body) in cases {
                if vname == "_" {
                    arms.push(format!("_ => {}", gen_expr(body, ctx)));
                } else {
                    arms.push(format!(
                        "{}::{} => {}",
                        ty_name,
                        to_pascal(vname),
                        gen_expr(body, ctx)
                    ));
                }
            }
            format!(
                "match {} {{ {} }}",
                maybe_paren(&gen_expr(value, ctx)),
                arms.join(", ")
            )
        }
        Expr::MapLit(_, _, entries, _) => {
            if entries.is_empty() {
                "HashMap::new()".to_string()
            } else {
                let mut s = String::from("{ let mut __m = HashMap::new();");
                for (k, v) in entries {
                    s.push_str(&format!(
                        " __m.insert({}, {});",
                        gen_expr(k, ctx),
                        gen_expr(v, ctx)
                    ));
                }
                s.push_str(" __m }");
                s
            }
        }
        Expr::Set(m, k, v, _) => format!(
            "{{ let mut __m = {}; __m.insert({}, {}); __m }}",
            gen_expr(m, ctx),
            gen_expr(k, ctx),
            gen_expr(v, ctx)
        ),
        Expr::Lookup(m, k, _) => format!(
            "{}.get(&{}).cloned().ok_or(())",
            maybe_paren(&gen_expr(m, ctx)),
            maybe_paren(&gen_expr(k, ctx))
        ),
        Expr::Contains(m, k, _) => format!(
            "{}.contains_key(&{})",
            maybe_paren(&gen_expr(m, ctx)),
            maybe_paren(&gen_expr(k, ctx))
        ),
        Expr::Remove(m, k, _) => format!(
            "{{ let mut __m = {}; __m.remove(&{}); __m }}",
            gen_expr(m, ctx),
            maybe_paren(&gen_expr(k, ctx))
        ),
        Expr::Keys(m, _) => format!(
            "{}.keys().cloned().collect::<Vec<_>>()",
            maybe_paren(&gen_expr(m, ctx))
        ),
        Expr::Unwrap(x, _) => format!(
            "{}.expect(\"[alva] unwrap on Err\")",
            maybe_paren(&gen_expr(x, ctx))
        ),
        Expr::ErrValue(x, _) => format!(
            "{{ match {} {{ Ok(__v) => panic!(\"[alva] err-value on Ok\"), Err(__e) => __e }} }}",
            gen_expr(x, ctx)
        ),
        Expr::Slice(v, s, e, _) => format!(
            "{}[{} as usize..{} as usize].to_vec()",
            maybe_paren(&gen_expr(v, ctx)),
            maybe_paren(&gen_expr(s, ctx)),
            maybe_paren(&gen_expr(e, ctx))
        ),
        Expr::Split(s, sep, _) => format!(
            "{}.split(&{}).map(|x| x.to_string()).collect::<Vec<String>>()",
            maybe_paren(&gen_expr(s, ctx)),
            maybe_paren(&gen_expr(sep, ctx))
        ),
        Expr::Concat(a, b, _) => format!(
            "format!(\"{{}}{{}}\", {}, {})",
            gen_expr(a, ctx),
            gen_expr(b, ctx)
        ),
        Expr::ToString(x, _) => format!("format!(\"{{}}\", {})", gen_expr(x, ctx)),
        Expr::ParseInt(x, _) => format!(
            "{{ let __s = {}; __s.trim().parse::<i64>().map_err(|e| format!(\"cannot parse int: {{e}}\")) }}",
            gen_expr(x, ctx)
        ),
        Expr::ToBytes(x, _) => format!("{}.into_bytes()", maybe_paren(&gen_expr(x, ctx))),
        Expr::IsOk(x, _) => format!("{}.is_ok()", maybe_paren(&gen_expr(x, ctx))),
        Expr::Join(v, sep, _) => format!(
            "{}.join(&{})",
            maybe_paren(&gen_expr(v, ctx)),
            maybe_paren(&gen_expr(sep, ctx))
        ),
        Expr::StripPrefix(s, p, _) => format!(
            "{}.strip_prefix(&{}).map(|x| x.to_string()).unwrap_or_else(|| {}.clone())",
            maybe_paren(&gen_expr(s, ctx)),
            maybe_paren(&gen_expr(p, ctx)),
            gen_expr(s, ctx)
        ),
        Expr::Before(s, sep, _) => format!(
            "{}.split(&{}).next().unwrap_or(\"\").to_string()",
            maybe_paren(&gen_expr(s, ctx)),
            maybe_paren(&gen_expr(sep, ctx))
        ),
        Expr::EndsWith(s, suf, _) => format!(
            "{}.ends_with(&{})",
            maybe_paren(&gen_expr(s, ctx)),
            maybe_paren(&gen_expr(suf, ctx))
        ),
        Expr::Sort(v, _) => {
            format!("{{ let mut __v = {}; __v.sort(); __v }}", gen_expr(v, ctx))
        }
        Expr::UrlDecode(x, _) => format!("glue::url_decode({})", gen_expr(x, ctx)),
        Expr::ToHex(x, _) => format!(
            "{{ let __b = {}; let mut __s = String::new(); for __x in &__b {{ __s.push_str(&format!(\"{{:02x}}\", __x)); }} __s }}",
            gen_expr(x, ctx)
        ),
        Expr::CtEq(a, b, _) => format!("glue::ct_eq({}, {})", gen_expr(a, ctx), gen_expr(b, ctx)),
        Expr::Loop(acc_name, acc_ty, init, inv, cond, body, _) => {
            let mut c2 = ctx.clone();
            c2.vars.insert(acc_name.clone(), "acc".to_string());
            let inv_check = match inv {
                Some(i) => format!(
                    "debug_assert!({}, \"loop invariant violated\");",
                    gen_expr(i, &c2)
                ),
                None => String::new(),
            };
            format!(
                "{{ let mut acc: {} = {}; {} while {} {{ {} acc = {}; {} }} acc }}",
                ty(acc_ty),
                gen_expr(init, ctx),
                inv_check,
                maybe_paren(&gen_expr(cond, &c2)),
                inv_check,
                gen_expr(body, &c2),
                inv_check
            )
        }
        Expr::Record(name, fields, _) => {
            let parts: Vec<String> = fields
                .iter()
                .map(|(n, v)| format!("{n}: {}", gen_expr(v, ctx)))
                .collect();
            format!("{} {{ {} }}", type_path(name), parts.join(", "))
        }
        Expr::Field(x, name, _) => {
            format!("{}.{name}.clone()", maybe_paren(&gen_expr(x, ctx)))
        }
        Expr::Raise(x, _) => format!("return Err({});", gen_expr(x, ctx)),
        Expr::Try(x, name, body, _) => {
            let mut c2 = ctx.clone();
            c2.vars.insert(name.clone(), "__e".to_string());
            format!(
                "match {} {{ Ok(__v) => __v, Err(__e) => {{ {} }} }}",
                maybe_paren(&gen_expr(x, ctx)),
                gen_expr(body, &c2)
            )
        }
        Expr::Ok(x, _) => format!("Ok({})", gen_expr(x, ctx)),
        Expr::Err(x, _) => format!("Err({})", gen_expr(x, ctx)),
    }
}

fn maybe_paren(s: &str) -> String {
    if s.chars().any(|c| c.is_whitespace()) || s.starts_with('{') {
        format!("({s})")
    } else {
        s.to_string()
    }
}

fn ty(te: &TypeExpr) -> String {
    match te {
        TypeExpr::Prim(p) => prim_rust(p).to_string(),
        TypeExpr::Named(n) => type_path(n),
        TypeExpr::Vec(t) => format!("Vec<{}>", ty(t)),
        TypeExpr::Map(k, v) => format!("HashMap<{}, {}>", ty(k), ty(v)),
        TypeExpr::Result(a, b) => format!("Result<{}, {}>", ty(a), ty(b)),
    }
}

// store.model.ObjectMeta -> crate::store_model::ObjectMeta
fn type_path(n: &str) -> String {
    if n.contains('.') {
        let last_dot = n.rfind('.').unwrap_or(0);
        format!(
            "crate::{}::{}",
            n[..last_dot].replace('.', "_"),
            &n[last_dot + 1..]
        )
    } else {
        n.to_string()
    }
}

fn to_pascal(s: &str) -> String {
    let mut out = String::new();
    let mut cap = true;
    for c in s.chars() {
        if c == '_' {
            cap = true;
        } else if cap {
            out.extend(c.to_uppercase());
            cap = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        out.push('X');
    }
    out
}

// 编译器内置运行时胶水：HTTP 服务器骨架（应用逻辑仍由语言层实现）
const GLUE_SOURCE: &str = r#"
mod glue {
    use std::io::{Read, Write};
    use std::net::{TcpListener, TcpStream};

    pub struct HttpRequest {
        pub method: String,
        pub path: String,
        pub query: String,
        pub headers: std::collections::HashMap<String, String>,
        pub body: Vec<u8>,
    }

    pub fn start_server(port: i64) -> u64 {
        let addr = format!("127.0.0.1:{}", port);
        let listener = TcpListener::bind(addr).unwrap();
        Box::into_raw(Box::new(listener)) as u64
    }

    pub fn accept_connection(handle: u64) -> u64 {
        let listener = unsafe { &*(handle as *const TcpListener) };
        match listener.accept() {
            Ok((stream, _)) => Box::into_raw(Box::new(stream)) as u64,
            Err(_) => 0,
        }
    }

    pub fn read_request(stream: u64) -> HttpRequest {
        let stream = unsafe { &mut *(stream as *mut TcpStream) };
        let mut buf = Vec::new();
        let mut tmp = [0u8; 4096];
        loop {
            let n = stream.read(&mut tmp).unwrap_or(0);
            if n == 0 {
                break;
            }
            buf.extend_from_slice(&tmp[..n]);
            if buf.windows(4).any(|w| w == b"\r\n\r\n") || buf.len() > (1 << 20) {
                break;
            }
        }
        let header_end = buf
            .windows(4)
            .position(|w| w == b"\r\n\r\n")
            .map(|p| p + 4)
            .unwrap_or(buf.len());
        let text = String::from_utf8_lossy(&buf[..header_end]);
        let mut lines = text.split("\r\n");
        let request_line = lines.next().unwrap_or("");
        let mut parts = request_line.split_whitespace();
        let method = parts.next().unwrap_or("").to_string();
        let raw_path = parts.next().unwrap_or("/");
        let (path, query) = match raw_path.split_once('?') {
            Some((p, q)) => (p.to_string(), q.to_string()),
            None => (raw_path.to_string(), String::new()),
        };
        let mut content_length = 0usize;
        let mut expect_continue = false;
        let mut headers = std::collections::HashMap::new();
        for line in lines {
            if let Some((name, value)) = line.split_once(':') {
                headers.insert(name.trim().to_ascii_lowercase(), value.trim().to_string());
            }
            let lower = line.to_ascii_lowercase();
            if let Some(v) = lower.strip_prefix("content-length:") {
                content_length = v.trim().parse().unwrap_or(0);
            }
            if lower.contains("expect:") && lower.contains("100-continue") {
                expect_continue = true;
            }
        }
        if expect_continue {
            let _ = stream.write_all(b"HTTP/1.1 100 Continue\r\n\r\n");
        }
        let mut body = buf[header_end..].to_vec();
        while body.len() < content_length {
            let n = stream.read(&mut tmp).unwrap_or(0);
            if n == 0 {
                break;
            }
            body.extend_from_slice(&tmp[..n]);
        }
        body.truncate(content_length);
        HttpRequest {
            method,
            path,
            query,
            headers,
            body,
        }
    }

    pub fn write_response(stream: u64, status: i64, content_type: String, body: Vec<u8>) -> i64 {
        let stream = unsafe { &mut *(stream as *mut TcpStream) };
        let reason = match status {
            200 => "OK",
            201 => "Created",
            204 => "No Content",
            400 => "Bad Request",
            404 => "Not Found",
            500 => "Internal Server Error",
            _ => "OK",
        };
        let head = format!(
            "HTTP/1.1 {} {}\r\nContent-Type: {}\r\nContent-Length: {}\r\nLast-Modified: Mon, 05 Jan 2026 00:00:00 GMT\r\nConnection: close\r\n\r\n",
            status,
            reason,
            content_type,
            body.len()
        );
        let _ = stream.write_all(head.as_bytes());
        let _ = stream.write_all(&body);
        status
    }

    pub fn write_head_response(stream: u64, status: i64, content_length: i64) -> i64 {
        let stream = unsafe { &mut *(stream as *mut TcpStream) };
        let reason = match status {
            200 => "OK",
            204 => "No Content",
            400 => "Bad Request",
            404 => "Not Found",
            _ => "OK",
        };
        let head = format!(
            "HTTP/1.1 {} {}\r\nContent-Length: {}\r\nLast-Modified: Mon, 05 Jan 2026 00:00:00 GMT\r\nConnection: close\r\n\r\n",
            status, reason, content_length
        );
        let _ = stream.write_all(head.as_bytes());
        status
    }

    pub fn close_stream(stream: u64) -> i64 {
        if stream != 0 {
            unsafe {
                drop(Box::from_raw(stream as *mut TcpStream));
            }
        }
        0
    }

    pub fn url_decode(s: String) -> String {
        let bytes = s.as_bytes();
        let mut out = Vec::with_capacity(bytes.len());
        let mut i = 0;
        while i < bytes.len() {
            if bytes[i] == b'%' && i + 2 < bytes.len() {
                let hi = (bytes[i + 1] as char).to_digit(16);
                let lo = (bytes[i + 2] as char).to_digit(16);
                if let (Some(h), Some(l)) = (hi, lo) {
                    out.push((h * 16 + l) as u8);
                    i += 3;
                    continue;
                }
            }
            out.push(bytes[i]);
            i += 1;
        }
        String::from_utf8_lossy(&out).to_string()
    }

    // 常量时间字符串比较（避免签名比较的时序侧信道）
    pub fn ct_eq(a: String, b: String) -> bool {
        let ab = a.as_bytes();
        let bb = b.as_bytes();
        if ab.len() != bb.len() {
            return false;
        }
        let mut diff = 0u8;
        for i in 0..ab.len() {
            diff |= ab[i] ^ bb[i];
        }
        diff == 0
    }

    // ---- minimal typed filesystem primitives (v0.3 durable storage) ----
    // These are the ONLY filesystem entry points the generated crate exposes.
    // The commit protocol, metadata transitions, recovery and GC live in the
    // alva storage modules, not here.

    fn err_storage(code: &str, msg: &str) -> String {
        format!("{code}:{msg}")
    }

    fn random_hex() -> String {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0);
        let c = COUNTER.fetch_add(1, Ordering::Relaxed);
        let x = (nanos ^ c.rotate_left(17)) ^ ((std::process::id() as u64) << 32);
        format!("{x:016x}{c:016x}")
    }

    fn to_hex(bytes: &[u8]) -> String {
        let mut s = String::with_capacity(bytes.len() * 2);
        for b in bytes {
            s.push_str(&format!("{b:02x}"));
        }
        s
    }

    pub fn fs_create_temp(dir: String, prefix: String) -> Result<String, String> {
        let dir = std::path::Path::new(&dir);
        std::fs::create_dir_all(dir)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("create tmp dir: {e}")))?;
        let path = dir.join(format!("{prefix}{}.tmp", random_hex()));
        std::fs::File::create(&path)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("create tmp file: {e}")))?;
        Ok(path.to_string_lossy().to_string())
    }

    pub fn fs_write_bytes(path: String, data: Vec<u8>) -> Result<i64, String> {
        use std::io::Write;
        let mut f = std::fs::OpenOptions::new()
            .write(true)
            .open(&path)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("open for write: {e}")))?;
        f.write_all(&data)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("write: {e}")))?;
        Ok(data.len() as i64)
    }

    pub fn fs_read_bytes(path: String) -> Result<Vec<u8>, String> {
        std::fs::read(&path).map_err(|e| err_storage("E_STORAGE_002", &format!("read: {e}")))
    }

    pub fn fs_read_string(path: String) -> Result<String, String> {
        std::fs::read_to_string(&path)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("read text: {e}")))
    }

    pub fn fs_file_size(path: String) -> Result<i64, String> {
        std::fs::metadata(&path)
            .map(|m| m.len() as i64)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("stat: {e}")))
    }

    pub fn fs_fsync_file(path: String) -> Result<i64, String> {
        std::fs::OpenOptions::new()
            .read(true)
            .write(true)
            .open(&path)
            .and_then(|f| f.sync_all())
            .map(|_| 0)
            .map_err(|e| err_storage("E_STORAGE_003", &format!("fsync file: {e}")))
    }

    pub fn fs_rename(src: String, dst: String) -> Result<i64, String> {
        std::fs::rename(&src, &dst).map(|_| 0).map_err(|e| {
            err_storage(
                "E_STORAGE_004",
                &format!("atomic rename {src} -> {dst}: {e}"),
            )
        })
    }

    pub fn fs_fsync_dir(path: String) -> Result<i64, String> {
        #[cfg(windows)]
        {
            // std::fs::File::sync_all() cannot flush directories on Windows
            // (FlushFileBuffers requires GENERIC_WRITE). Use kernel32 directly
            // with FILE_FLAG_BACKUP_SEMANTICS, which is the documented way to
            // open a directory handle and flush its metadata.
            use std::os::windows::ffi::OsStrExt;
            use std::ptr;
            const FILE_FLAG_BACKUP_SEMANTICS: u32 = 0x0200_0000;
            const GENERIC_WRITE: u32 = 0x4000_0000;
            const OPEN_EXISTING: u32 = 3;
            const INVALID_HANDLE_VALUE: isize = -1;
            #[link(name = "kernel32")]
            extern "system" {
                fn CreateFileW(
                    lp_file_name: *const u16,
                    dw_desired_access: u32,
                    dw_share_mode: u32,
                    lp_security_attributes: *mut std::ffi::c_void,
                    dw_creation_disposition: u32,
                    dw_flags_and_attributes: u32,
                    h_template_file: *mut std::ffi::c_void,
                ) -> isize;
                fn FlushFileBuffers(h_file: isize) -> i32;
                fn CloseHandle(h_object: isize) -> i32;
            }
            let wide: Vec<u16> = std::path::Path::new(&path)
                .as_os_str()
                .encode_wide()
                .chain(std::iter::once(0))
                .collect();
            let handle = unsafe {
                CreateFileW(
                    wide.as_ptr(),
                    GENERIC_WRITE,
                    0,
                    ptr::null_mut(),
                    OPEN_EXISTING,
                    FILE_FLAG_BACKUP_SEMANTICS,
                    ptr::null_mut(),
                )
            };
            if handle == INVALID_HANDLE_VALUE {
                return Err(err_storage(
                    "E_STORAGE_003",
                    &format!("fsync dir (open) {path}: {}", std::io::Error::last_os_error()),
                ));
            }
            let ok = unsafe { FlushFileBuffers(handle) };
            unsafe { CloseHandle(handle) };
            if ok == 0 {
                return Err(err_storage(
                    "E_STORAGE_003",
                    &format!("fsync dir (flush) {path}: {}", std::io::Error::last_os_error()),
                ));
            }
            Ok(0)
        }
        #[cfg(not(windows))]
        {
            std::fs::File::open(&path)
                .and_then(|f| f.sync_all())
                .map(|_| 0)
                .map_err(|e| err_storage("E_STORAGE_003", &format!("fsync dir: {e}")))
        }
    }

    pub fn fs_list_dir(path: String) -> Result<String, String> {
        let mut names = Vec::new();
        let rd = std::fs::read_dir(&path)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("read dir: {e}")))?;
        for entry in rd {
            let e = entry.map_err(|e| err_storage("E_STORAGE_002", &format!("read dir entry: {e}")))?;
            names.push(e.file_name().to_string_lossy().to_string());
        }
        names.sort();
        Ok(names.join("\n"))
    }

    pub fn fs_exists(path: String) -> bool {
        std::path::Path::new(&path).exists()
    }

    pub fn fs_mkdir_p(path: String) -> Result<i64, String> {
        std::fs::create_dir_all(&path)
            .map(|_| 0)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("mkdir: {e}")))
    }

    pub fn fs_remove(path: String) -> Result<i64, String> {
        match std::fs::remove_file(&path) {
            Ok(()) => Ok(0),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(0),
            Err(e) => Err(err_storage("E_STORAGE_002", &format!("remove: {e}"))),
        }
    }

    pub fn fs_remove_dir(path: String) -> Result<i64, String> {
        match std::fs::remove_dir(&path) {
            Ok(()) => Ok(0),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(0),
            Err(e) => Err(err_storage("E_STORAGE_002", &format!("remove dir: {e}"))),
        }
    }

    pub fn fs_env_string(name: String, default: String) -> String {
        std::env::var(&name).unwrap_or(default)
    }

    pub fn fs_secure_id() -> String {
        random_hex()
    }

    pub fn fs_sha256(data: Vec<u8>) -> String {
        use sha2::Digest;
        let mut h = sha2::Sha256::new();
        h.update(&data);
        to_hex(&h.finalize())
    }

    pub fn fs_sha256_file(path: String) -> Result<String, String> {
        use sha2::Digest;
        use std::io::Read;
        let mut f = std::fs::File::open(&path)
            .map_err(|e| err_storage("E_STORAGE_002", &format!("open blob: {e}")))?;
        let mut h = sha2::Sha256::new();
        let mut buf = [0u8; 65536];
        loop {
            let n = f
                .read(&mut buf)
                .map_err(|e| err_storage("E_STORAGE_002", &format!("read blob: {e}")))?;
            if n == 0 {
                break;
            }
            h.update(&buf[..n]);
        }
        Ok(to_hex(&h.finalize()))
    }

    // Deterministic crash failpoint: when ALVA_FAILPOINT == <name>, the process
    // exits immediately so tests can verify crash consistency at each commit stage.
    pub fn fs_failpoint(name: String) -> i64 {
        if let Ok(fp) = std::env::var("ALVA_FAILPOINT") {
            if fp == name.as_str() {
                eprintln!("FAILPOINT {name}");
                std::process::exit(17);
            }
        }
        0
    }
}
"#;

fn prim_rust(p: &Prim) -> &'static str {
    match p {
        Prim::U8 => "u8",
        Prim::U16 => "u16",
        Prim::U32 => "u32",
        Prim::U64 => "u64",
        Prim::I8 => "i8",
        Prim::I16 => "i16",
        Prim::I32 => "i32",
        Prim::I64 => "i64",
        Prim::F32 => "f32",
        Prim::F64 => "f64",
        Prim::Bool => "bool",
        Prim::String => "String",
        Prim::Bytes => "Vec<u8>",
        Prim::Nil => "()",
    }
}

fn rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    format!("{out}.to_string()")
}
